import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// NOTE: this is a nested layout under `app/DeliveryRules`.
// Nested layouts must NOT render <html> or <body> — only the root `app/layout.jsx` should.
export default function Layout({ children }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}>
      <main>{children}</main>
    </div>
  );
}